include parallelDefs

# required files
GLOBAL_REQUIRE = utils.h parallel.h sequence.h graph.h speculative_for.h graphUtils.h blockRadixSort.h
BENCH_REQUIRE = graphColorOrdering.h graphColorOrdering.C graphColor.h
LOCAL_REQUIRE = graphColorGreedy.h
OBJS = Coloring.o graphColorOrdering.o graphColorGreedy.o

include ../common/timeRequiredFiles
include MakeBench

