#!/usr/bin/python

bnchmrk="Coloring"
benchmark="Graph Coloring"
checkProgram="../common/ColoringCheck"
dataDir = "../graphData/data"

tests = [
    #[1, "randLocalGraph_J_5_10000000", "", ""],
    #[1, "rMatGraph_J_5_10000000", "", ""],
    #[1, "3Dgrid_J_10000000", "", ""],
    #[1, "starGraph_J_100000", "", ""]
		[1, "expGraph_J_10000000", "", ""]
		]

orderings = ["SSD", "R", "MSD", "SD"]

import runTests
for ordering in orderings:
	print(ordering)
	runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests, ordering)

