#!/usr/bin/python

bnchmrk="Coloring"
benchmark="Graph Coloring"
checkProgram="../common/ColoringCheck"
dataDir = "../graphData/data"

tests = [
#    [1, "starGraph_6", "", ""]
#     [1, "gridGraph_6", "", ""]
#    ,[1, "combGraph_6", "", ""]
#     , [1, "expGraph_4", "", ""]
#    ,[1, "powerGraph_4", "", ""]
#    ,[1, "randGraph_7", "", ""]
#    ,[1, "randLocalGraph_7", "", ""]
#    ,[1, "rMatGraph_7", "", ""]
     [1, "randLocalGraph_J_5_10000000", "", ""],
     [1, "rMatGraph_J_5_10000000", "", ""],
     [1, "3Dgrid_J_10000000", "", ""]
    #[1, "starGraph_100", "", ""]
    #[1, "expGraph_J_10000000", "", ""]
    #[1, "lineGraph_10", "", ""]
]

#orderings = ["SSD", "R", "MSD", "SD"]
orderings = ["LLF", "SLL"]

import runTests
for ordering in orderings:
	print(ordering)
	runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests, ordering)

